### PR TITLE
Update BetterAnimations.java

### PR DESCRIPTION
**Pull request by ellet0**
This remove unnecessary implements, I'm not 100% sure about it though, ModInitializer should be for both server and client, correct me if I'm wrong

### CODE REVIEW

**Comment by ellet0** [comment]
We also need to update this [file](https://github.com/kingmaj0r/KingsBetterAnimations/blob/main/src/main/resources/fabric.mod.json)

**Comment by kingmaj0r** [comment]
Im not sure about that currently, will have to look into it. Concering the update for fabric.mod.json, feel free to update it as needed

**Comment by kingmaj0r** [comment]
looking into this, it seems your correct indeed.

**Comment by kingmaj0r** [comment]
but its recommended to use onInitialize for code that is common to both environments.

**Comment by ellet0** [comment]
> We also need to update this [file](https://github.com/kingmaj0r/KingsBetterAnimations/blob/main/src/main/resources/fabric.mod.json)

Don't forget to update this file, my internet connection doesn't allow me to clone the repo, In updating using GitHub web

**Comment by kingmaj0r** [comment]
what needs updating in the fabric.mod.json? sorry im still new to coding mods in minecraft.

**Comment by ellet0** [comment]
> what needs updating in the fabric.mod.json? sorry im still new to coding mods in minecraft.

New and you seems to grow in Mc modding too fast

In the entrypoints, we will use the main instead of client and server arrays

**Comment by kingmaj0r** [comment]
Do you think we should create a custom player model so we can make our animations more realistic? so an example would be each arm would have 2 parts and the leg would have 2 parts too. so we could make more interesting animations kind of like mo bends https://www.curseforge.com/minecraft/mc-mods/mo-bends

**Comment by ellet0** [comment]
> Do you think we should create a custom player model so we can make our animations more realistic? so an example would be each arm would have 2 parts and the leg would have 2 parts too. so we could make more interesting animations kind of like mo bends https://www.curseforge.com/minecraft/mc-mods/mo-bends

I'm new to mc modding, but in general, I like the current implementation 

Only what it is missing is the sword attack in the first person

It will give a much better user experience if we could provide it

I can help you with that, but I don't plan on disappointing you because, like I said, I'm not familiar with mc and fabric api

**Comment by kingmaj0r** [comment]
Dont worry im new to it too, and sure i'll get the sword attack fixed in first person soon and how about we do the same feature but we make it so it could be disabled and can go back to the normal animations or semi-realistic animations? I personally think it would give the user better experince with more realistic animations but will have to look into it in the future, for now i'll work on getting that sword animation working. Thanks for all the push requests.

**Comment by kingmaj0r** [comment]
Hey @ellet0, i was looking into the mod and even testing it on my client witch was tested on Quilt 23.0 with minecraft 1.20.1 and i see the sword animation with no issues, could you please send me a gif or a video (not on youtube as my internet is restricted) showing me that it does not work.

mods i've used:
KingsBetterAnimations V1.2-BETA 1.20 - 1.20.4
FirstPersonModel 2.3.2 1.20.1

i've made a little video showing that the sword animation seems to work fine:

[Screencast from 2024-02-03 12-20-48.webm](https://github.com/kingmaj0r/KingsBetterAnimations/assets/49806509/88126dfd-4480-4fb3-9eaf-e52276f3cc7f)

**Comment by ellet0** [comment]
> Hey @ellet0, i was looking into the mod and even testing it on my client witch was tested on Quilt 23.0 with minecraft 1.20.1 and i see the sword animation with no issues, could you please send me a gif or a video (not on youtube as my internet is restricted) showing me that it does not work.
> 
> mods i've used:
> KingsBetterAnimations V1.2-BETA 1.20 - 1.20.4
> FirstPersonModel 2.3.2 1.20.1
> 
> i've made a little video showing that the sword animation seems to work fine:
> 
> [Screencast from 2024-02-03 12-20-48.webm](https://github.com/kingmaj0r/KingsBetterAnimations/assets/49806509/88126dfd-4480-4fb3-9eaf-e52276f3cc7f)

Yes, by first person, I meant without a third person model. By that, I mean without a first-person model mod

**Comment by ellet0** [comment]
To see what I mean, take a look at [Better Combat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)

**Comment by ellet0** [comment]
Take a look at [this](https://github.com/ZsoltMolnarrr/BetterCombat/pull/332)

To try it out on 1.20.4

**Comment by kingmaj0r** [comment]
Hey Ellet, very interesting indeed, i think i got a great idea, how about we try to merge KingsBetterAnimations with bettercombat allowing us to make compatibility easier and fixing the bug you have mentioned, because i think it would be possible to merge it into one mod and easier for us as you would be required to download one mod.

**Comment by ellet0** [comment]
> Hey Ellet, very interesting indeed, i think i got a great idea, how about we try to merge KingsBetterAnimations with bettercombat allowing us to make compatibility easier and fixing the bug you have mentioned, because i think it would be possible to merge it into one mod and easier for us as you would be required to download one mod.

That's is great, I have builded the jar file for 1.20.4

I did some workarounds

**Comment by ellet0** [comment]
This [file](https://github.com/kingmaj0r/KingsBetterAnimations/blob/main/src/main/java/KingMaj0r/betteranimations/IPlayerAccessor.java) could use docs comments

**Comment by kingmaj0r** [comment]
> > Hey Ellet, very interesting indeed, i think i got a great idea, how about we try to merge KingsBetterAnimations with bettercombat allowing us to make compatibility easier and fixing the bug you have mentioned, because i think it would be possible to merge it into one mod and easier for us as you would be required to download one mod.
> 
> That's is great, I have builded the jar file for 1.20.4
> 
> I did some workarounds
> 
> Let me know if you need me to send the jar to you

Hey ellet, no need, i will compile the jar myself and look into merging it into one but this could take a little while as merging to mods could be a be complex/complicated. I will update you with the progress as soon as i can.

**Pull request merged**
